In [1]:
import pandas as pd

In [80]:
rank_df = pd.read_csv("./results/rank.csv", index_col=[0])
rank_df.columns.name = "Date"
rank_df = rank_df.T
# rank.index = pd.to_datetime(rank.index)
# rank.index = rank.index.strftime("%Y-%m-%d")

In [81]:
def to_nivo(df):
    df_json = df.to_dict()
    nivo = []
    for team, ranks in df_json.items():
        team_dict = {"id": team, "data": []}
        for date, rank in ranks.items():
            team_dict["data"].append({"x": date, "y": rank})
        nivo.append(team_dict)
    return nivo

In [82]:
with open("./nivo_data/all_days_rank.json", "w") as f:
    f.write(str(to_nivo(rank_df)).replace("'", '"').replace("nan", "null"))

In [83]:
season_end_rank = rank_df.copy()
season_end_rank.index = pd.to_datetime(season_end_rank.index)
season_end_rank = season_end_rank.resample("Y").last()
season_end_rank.index = season_end_rank.index.strftime("%Y")

In [84]:
season_end_rank

Team,Chennai Super Kings,Delhi Capitals,Gujarat Lions,Gujarat Titans,Kochi Tuskers Kerala,Kolkata Knight Riders,Lucknow Super Giants,Mumbai Indians,Pune Warriors,Punjab Kings,Rajasthan Royals,Rising Pune Supergiant,Royal Challengers Bangalore,Sunrisers Hyderabad
Date,,,,,,,,,,,,,,
2008,3.0,5.0,NaN,NaN,NaN,6.0,NaN,4.0,NaN,2.0,1.0,NaN,7.0,8.0
2009,3.0,2.0,NaN,NaN,NaN,8.0,NaN,6.0,NaN,4.0,1.0,NaN,5.0,7.0
2010,2.0,3.0,NaN,NaN,NaN,8.0,NaN,1.0,NaN,7.0,4.0,NaN,5.0,6.0
2011,1.0,10.0,NaN,NaN,6.0,5.0,NaN,2.0,9.0,7.0,4.0,NaN,3.0,8.0
2012,1.0,5.0,NaN,NaN,NaN,2.0,NaN,3.0,9.0,6.0,7.0,NaN,4.0,8.0
2013,2.0,8.0,NaN,NaN,NaN,6.0,NaN,1.0,9.0,5.0,4.0,NaN,3.0,7.0
2014,1.0,8.0,NaN,NaN,NaN,3.0,NaN,4.0,NaN,2.0,5.0,NaN,6.0,7.0
2015,2.0,8.0,NaN,NaN,NaN,3.0,NaN,1.0,NaN,7.0,4.0,NaN,5.0,6.0
2016,NaN,7.0,5.0,NaN,NaN,3.0,NaN,1.0,NaN,8.0,NaN,6.0,4.0,2.0
2017,NaN,7.0,6.0,NaN,NaN,3.0,NaN,1.0,NaN,5.0,NaN,4.0,8.0,2.0
2018,1.0,8.0,NaN,NaN,NaN,3.0,NaN,4.0,NaN,6.0,5.0,NaN,7.0,2.0
2019,2.0,4.0,NaN,NaN,NaN,3.0,NaN,1.0,NaN,7.0,6.0,NaN,8.0,5.0
2020,2.0,3.0,NaN,NaN,NaN,4.0,NaN,1.0,NaN,7.0,6.0,NaN,8.0,5.0
2021,1.0,3.0,NaN,NaN,NaN,4.0,NaN,2.0,NaN,6.0,7.0,NaN,5.0,8.0
2022,7.0,3.0,NaN,1.0,NaN,6.0,2.0,8.0,NaN,9.0,5.0,NaN,4.0,10.0

In [85]:
with open("./nivo_data/season_end_rank.json", "w") as f:
    f.write(str(to_nivo(season_end_rank)).replace("'", '"').replace("nan", "null"))